### ISSUE TITLE
[Bug]: Connecting to the API isn't working anymore

### ISSUE THREAD

**Issue by RandomInternetPreson** [civitai/civitai#384] opened 2023-03-22 16:38 UTC
### What happened?

My code was running as usual, but around 11:40 today it stopped working.  Upon trying to get a response back form Civitai I am getting this error: schannel: next InitializeSecurityContext failed:

### Steps to reproduce the problem

(https://civitai.com/api/v1/models?limit=100&sort=Newest) trying to read from this link for example yields the above error.

### What should have happened?

I should have gotten a response from the server.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Google Chrome

### Additional information, context and logs

Everything had been working fine for a while, but now I am getting this error.

**Comment by manuelurenah** [comment] 2023-03-31 19:29
Closing since the issue is no longer happening

**Closed by manuelurenah** 2023-03-31 19:29 UTC
Labels: bug-report
