### ISSUE TITLE
[Bug]: api error

### ISSUE THREAD

**Issue by VeyDlin** [civitai/civitai#926] opened 2024-01-04 20:55 UTC
### What happened?

When using the api, I get an error when reading models from favorites

The error occurs on page 47, before and after that everything is fine

`{"message":"An unexpected error occurred","error":"Cannot read properties of undefined (reading 'file')"}`

### Steps to reproduce the problem

I have no idea, it seems to be about some kind of model, I can't find out more

### What should have happened?

the page is loaded

**Comment by BlafKing** [comment] 2024-01-05 11:46
I'm experiencing the same error when using any of the following sort options on the `models` endpoint: "Most Downloaded", "Most Liked", "Most Discussed", "Most Collected", "Most Images".

Only "Highest Rated" "Newest" and "Most Buzz" seem to work.

Example URL:
https://civitai.com/api/v1/models?sort=Most%20Downloaded

**Comment by dennzo** [comment] 2024-01-05 12:25
I am experiencing the same issue with some resources, here are two f models where it happens.    
Maybe it helps to pinpoint/isolate the problem.

```
https://civitai.com/api/v1/models/81458
https://civitai.com/api/v1/models/4384
```

**Comment by viralesveras** [comment] 2024-01-05 14:41
I also get this error on any non-trivial API access. This will do it for example:

```https://civitai.com/api/v1/models?limit=100&sort=Newest&page=2```

**Comment by BlafKing** [comment] 2024-01-05 14:46
It's caused by some certain models, I assume there was a change in a recent merge which the Public API does not yet support :/

**Comment by BlafKing** [comment] 2024-01-06 12:14
looks like the issue is now fixed.
I no longer experience any issues! :)

**Closed as completed** 2024-01-11 21:23 UTC
Labels: bug-report
